### ISSUE TITLE
how to use could use some more info

### ISSUE THREAD

**Issue by AaronMeyers** [domeccleston/langchain-ts-starter#3]
the README for this repo doesn't really fully get someone up and running. i didn't have turbo installed so first i got an error for the turbo command not being found... ok i solved that, but now when I try running the ``turbo run build lint check`` command, i get this error: 

Turbo error: error preparing engine: Could not find the following tasks in project: check

having a harder time finding the solution to that...

seems like some additional instructions could be helpful for this...

**Comment by domeccleston** [comment]
Hey @AaronMeyers good feedback. Will edit to make this clearer.

What were you looking to use Langchain for here?

**Comment by domeccleston** [comment]
Corrected Turborepo build commands and added instructions to run it with `npx`. Let me know if there's anything else I can help with @AaronMeyers

**Comment by AaronMeyers** [comment]
@domeccleston thanks! i have some experience with node and js, but i'm a little bit new to typescript.

this may be beyond the scope of a simple start project, but it would be ideal for me if there was a command that i could use to automatically re-compile changes and restart the server :)
